version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16.5
    working_directory: ~/project
    steps:
      - setup_remote_docker:
          version: 20.10.6
      - checkout
      - run:
          name: lint
          command: docker-compose -f docker-compose.ci.yml run --rm app lint
      - run:
          name: test
          command: docker-compose -f docker-compose.ci.yml run --rm app test
